[[pages]]
path = "home.py"
name = "About OpuSearch"
icon = "ğŸ“–"

[[pages]]
path = "pages/generation.py"
name = "Generate Alignments"
icon = "âš™ï¸"

[[pages]]
path = "pages/search.py"
name = "Search Alignments"
icon = "ğŸ”"

[[pages]]
path = "pages/external_drive.py"
name = "Use External Hard Drive"
icon = "ğŸ’¾"